.PHONY: all module demo run_demo test run_test clean rebuild

all: demo test

module: hashMap.o forwardList.o arrayList.o

hashMap.o: hashMap.cpp hashMap.h forwardList.h arrayList.h
	g++ -std=c++17 -Wall -Wextra -Wpedantic -O2 -c hashMap.cpp -o hashMap.o

forwardList.o: forwardList.cpp forwardList.h
	g++ -std=c++17 -Wall -Wextra -Wpedantic -O2 -c forwardList.cpp -o forwardList.o

arrayList.o: arrayList.cpp arrayList.h forwardList.h
	g++ -std=c++17 -Wall -Wextra -Wpedantic -O2 -c arrayList.cpp -o arrayList.o

demo: demo.o hashMap.o forwardList.o arrayList.o
	g++ -std=c++17 -Wall -Wextra -Wpedantic -O2 demo.o hashMap.o forwardList.o arrayList.o -o demo

demo.o: demo.cpp hashMap.h
	g++ -std=c++17 -Wall -Wextra -Wpedantic -O2 -c demo.cpp -o demo.o

run_demo: demo
	./demo

test: test.o hashMap.o forwardList.o arrayList.o
	g++ -std=c++17 -Wall -Wextra -Wpedantic -O2 test.o hashMap.o forwardList.o arrayList.o -o test

test.o: test.cpp hashMap.h
	g++ -std=c++17 -Wall -Wextra -Wpedantic -O2 -c test.cpp -o test.o

run_test: test
	./test

clean:
	rm -f *.o demo test log.txt

rebuild: clean all